#!/bin/bash

mkdir -p /etc/pki/tls/certs/

if [ ! -f /etc/pki/tls/certs/server.pem ]; then
	echo "Generating certificates ..."
	openssl req \
		-nodes \
		-x509 \
		-days 3650 \
		-newkey rsa \
		-keyout /etc/pki/tls/certs/server.key \
		-out /etc/pki/tls/certs/server.pem \
		-subj "/C=US/ST=CO/L=Denver/O=nbgallery/CN=nbgallery team/emailAddress=team@nb.gallery" 
fi

if [ -z "${NOTEBOOK_DIR}" ]; then
  NOTEBOOK_DIR='/root/notebook'
fi

mkdir -p "$NOTEBOOK_DIR"

exec jupyter notebook \
	--notebook-dir="$NOTEBOOK_DIR" \
	--certfile=/etc/pki/tls/certs/server.pem \
	--keyfile=/etc/pki/tls/certs/server.key \
	--JupyterApp.port=443 \
	--allow-root
